version: "2.2"

services:     
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017
  
  user-service:
    container_name: sh-user-service
    build: .
    env_file:
      - .env
    ports:
      - 5001:5001
    depends_on:
      - mongo
