version: "2.2"

services:     
  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:latest
    ports:
      - 27017:27017

  tor:
    container_name: tor
    image: dperson/torproxy:latest
    ports:
      - 9050:9050
  
  user-service:
    container_name: sh-user-service
    build: .
    env_file:
      - .env
    ports:
      - 5001:5001
    depends_on:
      - mongo
